### ISSUE TITLE
[Question] Count of filtered rows?

### ISSUE THREAD

**Issue by giuliohome** [pspro0305/Html-table-with-custom-filters#1]
Very cool implementation!
Thank you for sharing!
Is it simple to add a counter showing the number of filtered rows?

**Comment by pspro0305** [comment]
@giuliohome Yes it is simple to add a dynamic element say 
span with id="rowcount", just call the element and pass the count of visible columns
either by length or index of last table row.
P.S. I have updated the code, hope it helps.

**Comment by giuliohome** [comment]
Thank you very much!
Very interesting, I will try if I can use this inside my project.
I will let you know, thanks again, anyway!

**Comment by giuliohome** [comment]
Ops. you are not resetting the count when the filter is deleted with x or un-applied.
You are also counting as 1 even if there are no rows.
It would be awesome to have these fixed, if possible (otherwise close this issue again...)

**Comment by pspro0305** [comment]
@giuliohome I have made the updates in my new commit, thanks for the suggestion.

**Comment by giuliohome** [comment]
Thank you for sharing your cool repository, for the quick updates and the prompt repsonse!
